language: python
cache: apt
python:
  - pypy
notifications:
  irc: 
    channels:
      - "chat.freenode.net#pycket"
env:
  matrix:
    - TEST_TYPE=tests
    - TEST_TYPE=translate
    - TEST_TYPE=translate-nojit
before_install:
  - sudo add-apt-repository -y ppa:plt/racket
  - sudo apt-get update
  - sudo apt-get install -qq racket
install:
  - wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 -O `pwd`/../pypy.tar.bz2 || wget https://bitbucket.org/pypy/pypy/get/default.tar.bz2 -O `pwd`/../pypy.tar.bz2
  - tar -xf `pwd`/../pypy.tar.bz2 -C `pwd`/../
  - mv ../pypy-pypy* ../pypy
  - raco pkg install -t dir pycket/pycket-lang/
script:
  - export PYTHONPATH=$PYTHONPATH:../pypy:pycket
  - "case \"$TEST_TYPE\" in
       tests)
         ../pypy/pytest.py
         ;;
      translate)
        make translate-jit
        ;;
      translate-nojit)
        make translate-nojit
        ;;
    esac"

